### ISSUE TITLE
Questao 8 com problema

### ISSUE THREAD

**Issue by LucasSnatiago** [lusantisuper/ListasAED1#5]
A questão 8 está com um problema na produção da sequência. A partir do 95º valor gerado, a memória estoura e aparece valores incorretos, mesmo a variável sendo "long long int". 
Possivelmente, o erro está na forma em que é gerada a sequência de Fetuccine.

**Comment by Talkys** [comment]
Corrigido.

**Comment by lusantisuper** [comment]
Problema resolvido!

**Comment by LucasSnatiago** [comment]
Problema resolvido! Boa talkys!
